# Generated by Django 4.2.1 on 2023-05-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseReg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='registered_students', through='CourseReg.CourseRegistration', to='CourseReg.class'),
        ),
    ]
