# Generated by Django 4.2.1 on 2023-05-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseReg', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campus'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='core_courses',
        ),
        migrations.RemoveField(
            model_name='program',
            name='elective_courses',
        ),
        migrations.RemoveField(
            model_name='program',
            name='fundamental_courses',
        ),
        migrations.AddField(
            model_name='program',
            name='available_courses',
            field=models.ManyToManyField(blank=True, related_name='fundamental', to='CourseReg.course'),
        ),
    ]
