# Generated by Django 4.2.1 on 2023-05-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseReg', '0004_administrator_campus_type_course_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='reg_end',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='reg_start',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('course', 'campus')},
        ),
    ]
