# Generated by Django 4.2.1 on 2023-05-18 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseReg', '0005_remove_semester_reg_end_remove_semester_reg_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('weekend', 'Weekend')], max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='CourseReg.campus'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')]),
        ),
        migrations.AlterField(
            model_name='period',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='CourseReg.campus'),
        ),
        migrations.AlterField(
            model_name='room',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='CourseReg.campus'),
        ),
        migrations.RemoveField(
            model_name='semester',
            name='campus',
        ),
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')]),
        ),
        migrations.AddField(
            model_name='semester',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='CourseReg.campus'),
            preserve_default=False,
        ),
    ]
